WISDEM/WISDEM

tutorial-notebooks/01_cost_of_a_turbine.ipynb
tutorial-notebooks/02_cost_and_scaling.ipynb
tutorial-notebooks/03_betz_limit.ipynb
tutorial-notebooks/04_sellar.ipynb

Second draft of tutorials

---

.gitignore
wisdem/rotorse/rotor.py
wisdem/rotorse/rotor_geometry_yaml.py
wisdem/rotorse/turbine_inputs/BAR_200a_noRe.yaml

I made corrections to use a better method to determine blade stations locations with flaps.

Corrections for blade station location of TE Flaps

---

wisdem/towerse/tower.py

Git feature branch that fixed 3 small bugs in TowerSE identified during Ontology4All overhaul.  Bringing them into the Develop branch too.

Tower bugs

---

wisdem/assemblies/load_IEA_yaml.py
wisdem/assemblies/main.py
wisdem/assemblies/reference_turbines/optimization_options.yaml
wisdem/assemblies/run_tools.py
wisdem/assemblies/wt_land_based.py
wisdem/plant_financese/plant_finance.py
wisdem/towerse/tower.py

Most changes are in `main.py` and `tower.py` and focus on enabling tower optimizations using the new yaml format.
This is just a first pass; there might be more tower design variables, constraints, and objectives to add later.

Adding tower optimization options for yaml files

---

wisdem/assemblies/load_IEA_yaml.py
wisdem/commonse/utilities.py
wisdem/rotorse/rotor_elasticity.py
wisdem/rotorse/rotor_geometry_yaml.py
wisdem/rotorse/rotor_structure.py
wisdem/rotorse/rotor_structure_simple.py
wisdem/rotorse/rotor_visualization.py
wisdem/test/test_all.py
wisdem/test/test_yaml/__init__.py
wisdem/test/test_yaml/test_all.py
wisdem/test/test_yaml/test_monopile_derivs.py
wisdem/test/test_yaml/test_tower_derivs.py

- `arc_length()` was defined in multiple places and I refactored a few of the simple cases to using a single function
- I also added a corresponding derivative function for `arc_length()` and showed its use in `load_IEA_yaml.py` for two components by providing completed `compute_partials()` methods

Refactored arc_length and provided derivatives

---

wisdem/assemblies/main.py
wisdem/pyframe3dd/pyframe3dd.py
wisdem/rotorse/rail_transport.py
wisdem/rotorse/rotor_loads_defl_strains.py

swap E11 and E22

---

examples/blade/modeling_options.yaml
examples/reference_turbines_lcoe/modeling_options.yaml
wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py

More bos flags in the code to be able to skip the bos model if not required

bos flag on off

---

examples/blade/modeling_options.yaml
examples/reference_turbines_lcoe/modeling_options.yaml
wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/gc_RunTools.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py
wisdem/glue_code/runWISDEM.py
wisdem/schema/modeling_defaults.yaml
wisdem/schema/modeling_schema.yaml

Fixing a few problems that generated various bugs (wind estimator in rosco can be equal to 2, DriveSE is not always on, run_wisdem.py was not running)

driveSE flag + run wisdem working

---

examples/blade/modeling_options.yaml
examples/reference_turbines_lcoe/modeling_options.yaml
wisdem/aeroelasticse/openmdao_openfast.py
wisdem/ccblade/ccblade.py
wisdem/ccblade/ccblade_component.py
wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py
wisdem/schema/modeling_defaults.yaml
wisdem/schema/modeling_schema.yaml
wisdem/servose/servose.py

Revert "Ie aontology4all"

---

wisdem/glue_code/runWISDEM.py
wisdem/yaml/__init__.py
wisdem/yaml/gui.py

This is a workable version of the GUI for WISDEM.

Nested lists in gui

---

wisdem/ccblade/ccblade.py

Updates `af_flap_coords` function in ccblade.py to enable parallel processing.

Enable parallelization of xfoil calls

---

docs/examples/blade/tutorial.rst
docs/examples/refturb/tutorial.rst
docs/first_steps.rst
examples/02_reference_turbines/sample_plot.py
examples/03_blade/blade_driver.py
setup.py
wisdem/commonse/fileIO.py
wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/runWISDEM.py
wisdem/inputs/validation.py
wisdem/postprocessing/compare_designs.py

John's last PR inspired me to try to get the plotting scripts working with my file dumps.  With these changes, now we really can load in a previously run WISDEM files from the outputs.  You two might not use it much, but I probably will.

ennable loading of prior results and plotting

---

docs/inputs/analysis_schema.rst
examples/02_reference_turbines/analysis_options.yaml
examples/03_blade/analysis_options_aero.yaml
examples/03_blade/analysis_options_aerostruct.yaml
examples/03_blade/analysis_options_no_opt.yaml
examples/03_blade/analysis_options_struct.yaml
examples/05_tower_monopile/analysis_options.yaml
examples/05_tower_monopile/analysis_options_monopile.yaml
examples/09_weis_floating/analysis_options.yaml
wisdem/ccblade/ccblade_component.py
wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/gc_PoseOptimization.py
wisdem/glue_code/gc_WT_DataStruc.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/inputs/analysis_schema.yaml
wisdem/inputs/geometry_schema.yaml
wisdem/postprocessing/compare_designs.py
wisdem/postprocessing/default_analysis_options.yaml
wisdem/rotorse/parametrize_rotor.py
wisdem/rotorse/rotor_elasticity.py
wisdem/rotorse/rotor_structure.py
wisdem/test/test_ccblade/test_om_gradients.py
wisdem/test/test_gluecode/test_gc_loadinputs.py
wisdem/test/test_rotorse/test_rotor_structure.py

Switch from optimization_variables to design_variables in the analysis options yaml, in the code, and in the docs
Design variables is clearer and compatible to WEIS
Tests are passing

change opt variables to design variables

---

wisdem/glue_code/gc_WT_DataStruc.py

I commented out some of the print statements highlighting probable issues with the rotor structure. Issues that don't cause any issue to precomp, but most likely do in SONATA. I left them there so that they can be moved to a log of warnings once we setup one
Clean up the terminal from statements.

comment out warnings

---

wisdem/test/test_gluecode/test_gluecode.py

This should fix the tests
Update values of reg tests for NREL 5mw and tea 3.4mw
Tests should pass now

fix regression tests with new values

---

wisdem/commonse/vertical_cylinder.py
wisdem/pyframe3dd/src/py_io.c
wisdem/pyframe3dd/src/py_main.c
wisdem/test/test_towerse/test_tower.py

The submerged pile model has been working for years.  Mike McWilliams put me on the path to figure it out and fix it.

fix poor implementation of stiffness specified boundary conditions for soils

---

wisdem/glue_code/gc_WT_DataStruc.py

fix bug when HH does not match tower height
fix bug when HH does not match tower height

fix bug when HH does not match tower height

---

wisdem/glue_code/gc_PoseOptimization.py

The previous code had a typo that the tests didn't capture!
No hard coded indices

fix typo n_opt twice

---

wisdem/glue_code/gc_WT_DataStruc.py

Quick correction to scaling of tower for new hub height

fixing incorrect scaling of tower for new hub height

---

wisdem/glue_code/gc_WT_DataStruc.py

Delete the text explanations below these headers and replace them with information about your PR.
Please first consult the [developer guide](https://weis.readthedocs.io/en/latest/how_to_contribute_code.html) to make sure your PR follows all code, testing, and documentation conventions.
Explain the goal of this pull request. If it addresses an existing issue be sure to link to it. Describe the big picture of your changes here, perhaps using a bullet list if multiple changes are done to accomplish a single goal. If it accomplishes multiple goals, it may be best to create separate PR's for each. 
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the …

interpolate aerodynamic center

---

wisdem/postprocessing/compare_designs.py

Just adding the drag coefficient among the plots
Have cd among outputs

add drag coeff to post processing

---

wisdem/glue_code/gc_RunTools.py

Quick fix for OpenMDAO v3.8.0 API for case reading.

Update case reading for OpenMDAO v3.8.0

---

wisdem/glue_code/gc_PoseOptimization.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/inputs/analysis_schema.yaml
wisdem/rotorse/rotor_structure.py
wisdem/test/test_gluecode/test_gc_modified_yaml.py
wisdem/test/test_gluecode/test_gluecode.py

Fix a few bugs that emerged during some optimizations for the SOAR project. Garrett also fixed a bug in the computation of the strains
Run rotor design studies smoothly

Various bugs

---

wisdem/glue_code/gc_RunTools.py

The convergence trends plotting had incorrect logic introduced with the design of experiments PR.
I've fixed that here for both optimizations and DOEs.

Fixed faulty plotting logic

---

README.md
docs/installation.rst
wisdem/test/test_gluecode/test_drivers.py

Added NLOpt driver test at the yaml level.

Added nlopt driver test

---

wisdem/ccblade/ccblade.py
wisdem/ccblade/src/bem.f90
wisdem/test/test_ccblade/test_gradients.py
wisdem/test/test_gluecode/test_gc_modified_yaml.py
wisdem/test/test_gluecode/test_gluecode.py

Enforces unique values for Rhub, Rtip, precurveTip, and presweepTip to play nicely with CCBlade discretization (which makes this assumption) and derivative linearization

Ccblade tweaks

---

wisdem/rotorse/rotor_cost.py

Fix the indexing bug identified by Issue #273

initial index values to ints

---

environment.yml

Delete the text explanations below these headers and replace them with information about your PR.
Please first consult the [developer guide](https://weis.readthedocs.io/en/latest/how_to_contribute_code.html) to make sure your PR follows all code, testing, and documentation conventions.
Explain the goal of this pull request. If it addresses an existing issue be sure to link to it. Describe the big picture of your changes here, perhaps using a bullet list if multiple changes are done to accomplish a single goal. If it accomplishes multiple goals, it may be best to create separate PR's for each. 
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the …

hold openmdao at 3.8 to fix tests

---

examples/09_floating/modeling_options.yaml
examples/09_floating/modeling_options_noRNA.yaml
wisdem/commonse/utilization_dnvgl.py
wisdem/floatingse/floating.py
wisdem/floatingse/floating_frame.py
wisdem/floatingse/member.py
wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml
wisdem/inputs/modeling_schema.yaml
wisdem/test/test_floatingse/test_frame.py
wisdem/test/test_floatingse/test_member.py
wisdem/towerse/tower_struct.py

Add structural stress and buckling analysis to floatingSE.  The function to do the checks is separate from the Frame3DD call so that it can be used with OpenFAST outputs too.

Floating struct

---

wisdem/inputs/modeling_schema.yaml
wisdem/rotorse/rotor_power.py
wisdem/test/test_rotorse/test_rotor_power.py

Have the option to lock pitch in reg I1/2
Support Eliot's designs

Fix pitch reg i12

---

README.md

There was a typo in the readme
Maintenance

build status on GHA

---

wisdem/commonse/fileIO.py

Fixed deprecation warning in options in prob.list_inputs and prob.list_outputs.
- [] Bugfix (non-breaking change which fixes an issue)

complying with openmdao deprecation warnings

---

wisdem/glue_code/gc_LoadInputs.py

Delete the text explanations below these headers and replace them with information about your PR.
Please first consult the [developer guide](https://weis.readthedocs.io/en/latest/how_to_contribute_code.html) to make sure your PR follows all code, testing, and documentation conventions.
Explain the goal of this pull request. If it addresses an existing issue be sure to link to it. Describe the big picture of your changes here, perhaps using a bullet list if multiple changes are done to accomplish a single goal. If it accomplishes multiple goals, it may be best to create separate PR's for each. 
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the …

Generalize fix/ed keyword for MAP compatibility in WEIS

---

wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml

Allows users to set a minimum bound on AEP

Enable AEP as a constraint

---

examples/05_tower_monopile/monopile_direct.py
examples/09_floating/mooring_opt.py
examples/09_floating/semi_only_driver.py
examples/09_floating/spar_only_driver.py
examples/09_floating/spar_opt.py
examples/09_floating/tlp_example.py
wisdem/inputs/modeling_schema.yaml
wisdem/test/test_floatingse/test_member.py
wisdem/test/test_towerse/test_tower.py
wisdem/test/test_towerse/test_tower_struct.py
wisdem/towerse/tower_struct.py

Fix tests and OpenMDAO warnings

Fix tests and openmdao warnings

---

examples/09_floating/tlp_example.py
wisdem/floatingse/member.py
wisdem/glue_code/gc_WT_DataStruc.py
wisdem/inputs/analysis_schema.yaml
wisdem/inputs/geometry_schema.yaml
wisdem/test/test_floatingse/test_floating.py
wisdem/test/test_floatingse/test_member.py

To fix dimensional value of ring stiffeners to non-dimensional grid values, added comments.
We know some of the floating test cases will fail and would like feedback on how to resolve.

Fixed ring_stiffener non-dimensional issues

---

examples/09_floating/nrel5mw-spar_oc3.yaml
examples/12_pyframe3dd/exB.py
wisdem/commonse/distribution.py
wisdem/commonse/fileIO.py
wisdem/commonse/utilities.py
wisdem/floatingse/floating_frame.py
wisdem/floatingse/member.py
wisdem/test/test_examples/test_examples.py
wisdem/test/test_floatingse/test_frame.py
wisdem/test/test_floatingse/test_member.py

Changes to support the global DLC driver and freq domain execution in WEIS.

Weis support

---

examples/09_floating/IEA-15-240-RWT_VolturnUS-S.yaml
examples/16_inverse_design/analysis_options.yaml
examples/16_inverse_design/inverse_spar_design.py
wisdem/floatingse/floating_frame.py
wisdem/glue_code/gc_PoseOptimization.py
wisdem/glue_code/gc_WT_DataStruc.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py
wisdem/inputs/analysis_schema.yaml
wisdem/inputs/geometry_schema.yaml
wisdem/test/test_examples/test_examples.py
wisdem/test/test_floatingse/test_frame.py

- Includes the transition piece mass / MofI / cost in platform totals.
- Calculate moments of inertia for water (variable) ballast
- Include water ballast MofI in platform total (now have separate "hull" and "total" MofI values)

Include water ballast and transition piece in platform totals

---

wisdem/floatingse/floating_frame.py
wisdem/pyframe3dd/pyframe3dd.py

Fixes connectivity failures that can arise during optimization

Connectivity update on every iteration

---

examples/02_reference_turbines/iea10mw_driver.py
examples/02_reference_turbines/modeling_options_iea10.yaml
wisdem/test/test_examples/test_examples.py

Didn't realize the IEA10 wasn't part of regular tests and it was failing due to mismatch with the regular modeling_options

adding iea10 dedicated modeling options and adding to regular tests

---

wisdem/ccblade/Polar.py
wisdem/drivetrainse/drivetrain.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py
wisdem/inputs/modeling_schema.yaml
wisdem/rotorse/rail_transport.py
wisdem/rotorse/rotor_cost.py
wisdem/rotorse/rotor_elasticity.py
wisdem/test/test_rotorse/test_rail_transport.py

Small PR to fix a few (minor) bugs and situations where exceptions were raised:
* the Xt and Xc for the hub/spinner material are only taken in direction 1 and 2, not 3 (this is often n/a)
* An error in Polar.py was unnecessarily triggered for the 3d correction
* the rotor cost model is improved
* the rail transport model is refreshed (work needs to be completed here)
Support projects BAR, AMERICA, INN, etc

Drivetrain error

---

wisdem/glue_code/runWISDEM.py

Return error if user provides more cores in the mpi call than finite differences
Strengthen parallelization

Parallelization

---

wisdem/glue_code/gc_LoadInputs.py
wisdem/postprocessing/wisdem_get.py

Small bug fixes to make sure 15-MW postprocessing scripts still work

changes associated with the new fixedbottomse required for 15-mw scripts

---

wisdem/glue_code/glue_code.py
wisdem/rotorse/rotor_power.py

Fix bug in the connection of layer thicknesses to rotor cost
Fix bug

fix bug in layer thickness correction

---

examples/09_floating/nrel5mw-spar_oc3.yaml
wisdem/glue_code/gc_LoadInputs.py

Closing out the changes required to fix bugs and keep in-step with RAFT

Changes for Level1 in WEIS

---

wisdem/rotorse/rotor_power.py

rotor power uses coned tip for the max tip speed

R tip takes into account rotor preconing

---

wisdem/glue_code/gc_PoseOptimization.py

Downgrading a fatal error to a warning.

Code should still run with DVs true but driver false

---

wisdem/glue_code/gc_PoseOptimization.py
wisdem/glue_code/gc_RunTools.py
wisdem/glue_code/gc_WT_DataStruc.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py
wisdem/inputs/analysis_schema.yaml
wisdem/towerse/tower.py

Changes needed for the current CCD studies in WEIS to set the floating platform members as constant diameter and allow the optimizer to control them.

Allow for constant diameter floatingSE members

---

wisdem/airfoilprep/airfoilprep.py
wisdem/ccblade/ccblade.py
wisdem/test/test_ccblade/test_gradients.py
wisdem/test/test_ccblade/test_om_gradients.py

This PR aligns the WISDEM and CCBlade repos with some added checks and cleanup stemming from an issue posted there.  No change in functionality.

Code robustness and cleanup from ccblade repo

---

wisdem/rotorse/precomp.py

Fix esoteric bug that appeared in PreComp for fallback airfoils and large twist angles
Support ARPA-E Atlantis project from NJ

avoid bug in airfoil interpolation

---

examples/02_reference_turbines/IEA-10-198-RWT.yaml
examples/02_reference_turbines/IEA-15-240-RWT.yaml
examples/02_reference_turbines/IEA-3p4-130-RWT.yaml
examples/02_reference_turbines/nrel5mw.yaml
examples/03_blade/BAR_USC.yaml
examples/09_floating/IEA-15-240-RWT_VolturnUS-S.yaml
examples/09_floating/nrel5mw-semi_oc4.yaml
examples/09_floating/nrel5mw-spar_oc3.yaml
wisdem/test/test_gluecode/test_gluecode.py

Quick bug fix in the labels of the geometry yamls
Support LTS work

Distance mb

---

examples/03_blade/BAR_USC.yaml
wisdem/rotorse/blade_cost.py

minor branch, merge and delete

update bar usc

---

wisdem/commonse/cylinder_member.py
wisdem/floatingse/floating_frame.py
wisdem/floatingse/floating_system.py
wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml

A few more small improvements for robustness when doing optimization of the platform with FloatingSE

Additional tweaks for more robust platform optimization with FloatingSE

---

wisdem/glue_code/gc_LoadInputs.py

Fix bug in inertia matrix
Fix bug identified in https://github.com/WISDEM/WISDEM/issues/377

fix bug in inertia matrix

---

wisdem/commonse/environment.py
wisdem/fixed_bottomse/monopile.py
wisdem/inputs/geometry_schema.yaml
wisdem/orbit/api/wisdem.py
wisdem/orbit/manager.py
wisdem/test/test_fixed_bottomse/test_monopile.py

Fix bugs in monopile soil springs calculation

FixedBottomSE bugs

---

wisdem/commonse/cylinder_member.py
wisdem/fixed_bottomse/monopile.py
wisdem/floatingse/floating.py
wisdem/test/test_fixed_bottomse/test_monopile.py
wisdem/towerse/tower.py

Caught one more bug that should have been fixed prior to the 3.6 release

Fix bug in hydrostatic load calcs

---

setup.py
wisdem/postprocessing/compare_designs.py
wisdem/postprocessing/wisdem_get.py

Errors highlighted by IEA-15 CI tests

correcting some variable references after changes

---

examples/06_drivetrain/drivetrain_direct.py
examples/06_drivetrain/drivetrain_geared.py
wisdem/drivetrainse/drive_structure.py
wisdem/drivetrainse/drivetrain.py
wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml
wisdem/test/test_drivetrainse/test_drive_structure.py
wisdem/test/test_rotorse/test_blade_cost.py

Creates additional design constraints around allowed deflection and angular (non-torque) rotation of the shaft at the generator rotor connection and the bedplate at the stator connection.

Set deflection and rotation limits for drivetrain shaft-rotor and bedplate-stator connection

---

.github/workflows/CI_WISDEM.yml
README.md
docs/installation.rst
environment.yml
pyproject.toml
wisdem/fixed_bottomse/jacket.py
wisdem/glue_code/glue_code.py

Adding a few more outputs to the jacket module so that WEIS can use it.

more outputs from jacket module for connection to weis

---

docs/requirements.txt
environment.yml

Would this fix the wisdem docs?
Fix the wisdem docs by adding dependencies to the wisdem env yaml

add dependencies to env

---

examples/06_drivetrain/drivetrain_direct.py
wisdem/glue_code/gc_LoadInputs.py
wisdem/test/test_optimization_drivers/test_nlopt_driver.py

User-defined parameters, such as generator specs, or cost number overrides should be written out into the output yaml for reuse.

Write-out user-defined parameters in output yaml

---

meson.build
wisdem/glue_code/gc_WT_InitModel.py
wisdem/inputs/analysis_schema.yaml
wisdem/inputs/geometry_schema.yaml

Improving install robustness and other bug fixes that arose in WEIS work.

Bug fixes for WEIS

---

wisdem/commonse/mpi_tools.py

I mistakenly merged in the wrong mph code to support running openfast with openmp. This piece of code should really live in WEIS, but to avoid code duplication is hosted in the wisdem repo

openmp script was outdated

---

wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml
wisdem/rotorse/rotor_power.py

Allow coefficient of thrust to be used as a constraint function & output

Thrust-constrained optimization changes

---

wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/rotorse/rotor_elasticity.py

Fix some bugs in handling of start and end nd arc points for composite layers
Tests are passing

Precomp bug

---

examples/05_tower_monopile/monopile_direct.py
examples/06_drivetrain/drivetrain_geared.py
examples/17_jacket/analysis_options_jacket.yaml
examples/18_rotor_tower_monopile/analysis_options.yaml
wisdem/pyframe3dd/pyframe3dd.py

Changes to example settings to accelerate the CI tests.

Speed up CI tests

---

.github/workflows/CI_WISDEM.yml
.github/workflows/Publish_WISDEM.yml
pyproject.toml
setup.py

Make WISDEM pip installable!
- [] Bugfix (non-breaking change which fixes an issue)

Build scripts for auto uploading to PyPi upon release tagging

---

wisdem/inputs/geometry_schema.yaml

Axis description

---

wisdem/glue_code/glue_code.py

Minor clean up of some if conditions to support bjs (blade joint sizer) module

tune if conditions bjs

---

examples/19_rotor_drivetrain_tower/analysis_options.yaml
examples/19_rotor_drivetrain_tower/modeling_options.yaml
examples/19_rotor_drivetrain_tower/wisdem_driver.py
wisdem/rotorse/rotor_structure.py
wisdem/test/test_examples/test_examples.py

Add example #19 where blade, drivetrain, and tower wall thickness are optimized simultaneously

Example 19

---

.github/workflows/CI_WISDEM.yml
.github/workflows/Publish_WISDEM.yml
wisdem/drivetrainse/drive_components.py
wisdem/drivetrainse/drive_structure.py
wisdem/glue_code/gc_PoseOptimization.py
wisdem/glue_code/glue_code.py
wisdem/postprocessing/compare_designs.py
wisdem/rotorse/rotor.py
wisdem/rotorse/rotor_elasticity.py
wisdem/rotorse/rotor_power.py
wisdem/rotorse/rotor_structure.py
wisdem/test/test_drivetrainse/test_components.py
wisdem/test/test_drivetrainse/test_drive_structure.py
wisdem/test/test_drivetrainse/test_drivetrainse.py
wisdem/test/test_gluecode/test_gc_modified_yaml.py
wisdem/test/test_gluecode/test_gc_yaml_floating.py
wisdem/test/test_gluecode/test_gluecode.py
wisdem/test/test_rotorse/test_BladeJointSizing.py
wisdem/test/test_rotorse/test_rotor_structure.py

Calculate the cg of the blade along the span and use that to estimate the cg of all blades along the shaft axis (in hub coordinate system) to have a more accurate cg estimate of the nacelle.

Add in calculation of cg of blades with coning and blade curvature

---

examples/03_blade/analysis_options_aero.yaml
examples/03_blade/analysis_options_aerostruct.yaml
examples/03_blade/analysis_options_struct.yaml
examples/05_tower_monopile/analysis_options.yaml
examples/05_tower_monopile/analysis_options_monopile.yaml
examples/09_floating/analysis_options.yaml
examples/09_floating/analysis_options_mooropt.yaml
examples/09_floating/analysis_options_semiopt.yaml
examples/09_floating/analysis_options_sparopt.yaml
examples/16_inverse_design/analysis_options.yaml
examples/17_jacket/analysis_options_jacket.yaml
examples/19_rotor_drivetrain_tower/analysis_options.yaml

Delete the text explanations below these headers and replace them with information about your PR.
Please first consult the [developer guide](https://weis.readthedocs.io/en/latest/how_to_contribute_code.html) to make sure your PR follows all code, testing, and documentation conventions.
Explain the goal of this pull request. If it addresses an existing issue be sure to link to it. Describe the big picture of your changes here, perhaps using a bullet list if multiple changes are done to accomplish a single goal. If it accomplishes multiple goals, it may be best to create separate PR's for each.
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the …

try reducing testing time

---

examples/02_reference_turbines/IEA-15-240-RWT.yaml
examples/03_blade/BAR_USC.yaml
examples/03_blade/analysis_options_aero.yaml
examples/03_blade/analysis_options_aerostruct.yaml
examples/03_blade/analysis_options_struct.yaml
examples/05_tower_monopile/analysis_options.yaml
examples/05_tower_monopile/analysis_options_monopile.yaml
examples/09_floating/IEA-15-240-RWT_VolturnUS-S.yaml
examples/09_floating/analysis_options.yaml
examples/09_floating/analysis_options_mooropt.yaml
examples/09_floating/analysis_options_semiopt.yaml
examples/09_floating/analysis_options_sparopt.yaml
examples/16_inverse_design/analysis_options.yaml
examples/17_jacket/analysis_options_jacket.yaml
examples/18_rotor_tower_monopile/IEA15MW_FB.yaml
examples/18_rotor_tower_monopile/IEA15MW_FB_scaled.yaml
examples/19_rotor_drivetrain_tower/analysis_options.yaml
wisdem/glue_code/gc_WT_DataStruc.py
wisdem/inputs/geometry_schema.yaml
wisdem/test/test_gluecode/test_gluecode.py
wisdem/test/test_rotorse/test_BladeJointSizing.py

Define wind turbine rotor diameter as hub diameter plus two times the projected blade length (and no longer the curved blade length). Reduce max iteration number to 1 in the examples to cut 1 hours of testing time
- [] New feature (non-breaking change which adds functionality)

Rotor D defined along projected blade

---

.github/workflows/Publish_WISDEM.yml
README.md
docs/installation.rst
pyproject.toml

pypi doesn't work for WISDEM on Mac ARM.  This is supposed to fix that, but I'm not 100% positive.

better architecture coverage on pypi

---

wisdem/ccblade/meson.build
wisdem/meson.build
wisdem/pyframe3dd/meson.build
wisdem/rotorse/meson.build

Follow lead of scipy on how to do this a bit better.

better f2py support

---

wisdem/commonse/fileIO.py
wisdem/glue_code/gc_PoseOptimization.py

Restore the intermediate variables in the output files that are inputs to some modules, but connected to outputs of others and are therefore not IndepVarComps.

More variables

---

docs/examples/05_tower_mono/tutorial.rst
docs/wisdem/towerse/intro.rst

Per issue #500, improve the tower example documentation around the coordinate system for the RNA properties and loading.

Updating documentation per issue suggestion

---

docs/wisdem/drivetrainse/layout.rst
wisdem/glue_code/gc_LoadInputs.py
wisdem/postprocessing/compare_designs.py

* Fix compare_designs script so that all struct layers are printed out
* Fix WEIS example 09 design of experiment https://github.com/WISDEM/WEIS/issues/276
* Update docs formula for bedplate height

Compare designs

---

environment.yml
examples/15_step_size_study/driver.py
pyproject.toml
wisdem/optimization_drivers/nlopt_driver.py
wisdem/test/test_optimization_drivers/test_nlopt_driver.py

I'm hoping this fixes the issue with the readthedocs build and also syncs to the latest OpenMDAO releases that have the bug fix we have been waiting for.

Update omdao ver and fix docs build

---

.github/workflows/Publish_WISDEM.yml
pyproject.toml
wisdem/commonse/mpi_tools.py
wisdem/drivetrainse/drive_components.py
wisdem/inputs/gui.py
wisdem/rotorse/rotor_power.py
wisdem/test/test_gluecode/test_gc_modified_yaml.py
wisdem/test/test_gluecode/test_gc_yaml_floating.py

Errors were pointed out in the prior release.

Fix errors in 3.15 release

---

.github/workflows/Publish_WISDEM.yml
docs/examples/10_ccblade/tutorial.rst
pyproject.toml

Fix outdated reference to ccblade init from file observed in #525

Ccblade docs

---

.github/workflows/Publish_WISDEM.yml
pyproject.toml

Per #531 , the community would like to use WISDEM inside Docker and that currently isn't supported with pip install.

try to expand linux build archs for docker support

---

wisdem/commonse/cylinder_member.py

This PR fixes the unit in Memberdiscretization.

Fixed unit connection

---

wisdem/inputs/validation.py
wisdem/test/test_inputs/sample.yaml
wisdem/test/test_inputs/test_validation.py

More robust yaml reader/validator to accept either a Path object or a string (from [here](https://github.com/WISDEM/WEIS/issues/282)).

accept Path or string

---

wisdem/inputs/validation.py

Some quick readability improvements to the parsing code for windIO input file (containing turbine and farm level information) implemented in this work. Specifically, the following were added
- docstrings for functions
- type hints in function signature
- quick refactoring to make the logic more compact/idiomatic python 

Improve windIO input file validation script

---

examples/05_tower_monopile/monopile_direct.py
examples/05_tower_monopile/tower_direct.py
wisdem/fixed_bottomse/monopile.py
wisdem/floatingse/floating_frame.py
wisdem/inputs/modeling_schema.yaml
wisdem/test/test_fixed_bottomse/test_monopile.py
wisdem/test/test_towerse/test_tower.py
wisdem/towerse/tower.py

Previous PR on this change wasn't as complete as it should have been.  This elevates the rank_and_file option to user options.

Complete options for rank_and_file

---

docs/examples.rst
docs/examples/11_user_custom/tutorial.rst
docs/examples/16_inverse_design/tutorial.rst
examples/11_user_custom/analysis_options_custom.yaml
examples/11_user_custom/user_custom_opt.py
wisdem/ccblade/Polar.py
wisdem/commonse/utilities.py
wisdem/inputs/geometry_schema.yaml
wisdem/test/test_examples/test_examples.py

This PR adds a new example 11 (previous example 11 had been deleted) where custom-set design variable, figure of merit, and constraint are set by the user. This is in support of a WEIS milestone due on June 30th. A readme file will be soon added to WEIS pointing to this example.

User custom

---

wisdem/landbosse/landbosse_omdao/landbosse.py

Same as https://github.com/WISDEM/LandBOSSE/pull/194

remove rounding at the end of landbosse

---

wisdem/commonse/cross_sections.py
wisdem/commonse/cylinder_member.py

This PR fixed two bugs for rectangular members.

Bug fixes for rectangular members

---

examples/09_floating/IEA-15-240-RWT_VolturnUS-S.yaml
pyproject.toml
wisdem/commonse/utilities.py
wisdem/fixed_bottomse/monopile.py
wisdem/floatingse/floating.py
wisdem/floatingse/floating_frame.py
wisdem/glue_code/glue_code.py
wisdem/inputs/modeling_schema.yaml
wisdem/rotorse/rotor_structure.py
wisdem/test/test_commonse/test_utilities.py
wisdem/test/test_fixed_bottomse/test_monopile.py
wisdem/test/test_floatingse/test_floating.py
wisdem/test/test_towerse/test_tower.py
wisdem/towerse/tower.py

Still a couple of bug fixes for the 3.16 features including the new glue code, especially for some floating calculations and a reset of the modal coefficients.

Fix urgent bugs

---

pyproject.toml
wisdem/fixed_bottomse/monopile.py
wisdem/floatingse/floating_frame.py

Final bug fix of 3.16 release (hopefully) around modal coefficients.

Fix last bugs of 3.16 release

---

wisdem/glue_code/runWISDEM.py

Addresses #549, but think there is a deeper issue with MPI on Windows at foot.

only check about cores and ndv with mpi when doing optimization

---

wisdem/inputs/validation.py

This PR adjusts the `simple_types` utility to revert numpy primatives to python primatives.
Seemed to pass testing on my machine.

fixing gaps in simple_types

---

wisdem/commonse/cross_sections.py
wisdem/commonse/environment.py
wisdem/fixed_bottomse/jacket.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/runWISDEM.py
wisdem/inputs/validation.py
wisdem/landbosse/model/CollectionCost.py
wisdem/landbosse/model/ErectionCost.py
wisdem/landbosse/model/FoundationCost.py
wisdem/landbosse/model/SitePreparationCost.py
wisdem/main.py
wisdem/rotorse/rotor_power.py

bug in start end layer error message

---

environment.yml
pyproject.toml

Incrementing version number and removing numpy limitations.  Looks like conda will still use numpy 1.x if you use the `environment.yml` file because of other packages (maybe `pyoptsparse`?) for now.

prep for next release

---

wisdem/inputs/validation.py

Support the TurbOEM work, where we change dictionaries across different WISDEM calls. Without this change, one change in a flag gets unintentionally propagated to other flags that simply share a pointer in the original yaml or in the schema

break shared references from yaml anchors and pointers

---

.github/workflows/CI_WISDEM.yml
README.md
wisdem/glue_code/gc_LoadInputs.py
wisdem/glue_code/gc_RunTools.py
wisdem/glue_code/gc_WT_InitModel.py
wisdem/glue_code/glue_code.py
wisdem/glue_code/runWISDEM.py
wisdem/orbit/core/library.py
wisdem/rotorse/parametrize_rotor.py
wisdem/rotorse/rotor_structure.py

A mix of changes supporting the next release of TurbOEM. Mostly, this is cleaning up some print to screens. I've also improved the formulation of the chord slope constraint and added a check if a layer is set to be optimized but does not exist.

Clean screen

---

examples/09_floating/IEA-15-240-RWT_VolturnUS-S.yaml
wisdem/glue_code/gc_WT_InitModel.py
wisdem/inputs/geometry_schema.yaml

This PR allows scalar coefficients for floating members.
The IEA 15 MW example now has mixed definitions.
Not all tests pass, but the same failures were observed before these changes.

Allow scalar coefficients for floating members

---

wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml
wisdem/rotorse/parametrize_rotor.py

Add twist slope constraint as suggested in issue #604 

Twist slope

---

wisdem/glue_code/gc_PoseOptimization.py
wisdem/inputs/analysis_schema.yaml

Update options setting for pyoptsparse and snopt. Set up the output files folder correctly and added some snopt options.
Work as expected when running optimizations on kestrel.

Snopt and pyoptsparse option setting updates

---

wisdem/inputs/gui.py

The GUI can now be used for plotting!  This is something I've long wanted to do and have poked at here and there.

add ability to quickly plot outputs to gui

---

wisdem/glue_code/runWISDEM.py

Set work_dir in openmdao 3.38.0

set working directory

---

wisdem/glue_code/gc_RunTools.py

The plotting routine for the .sql file was previously failing for 3D arrays. I've added a logic to go around this limitation

Plot iterdata

---

wisdem/rotorse/rotor_power.py

@ewquon was running into an error that occurs when cut-in is too close to rated

add logic to avoid error when cut in is close to rated wind speed

---

.github/workflows/Publish_WISDEM.yml

The setup-fortran action moved to the @fortran-lang org, my original repo will continue working, but it is recommended to change to the new repository.

Update setup-fortran action

---

wisdem/drivetrainse/layout.py
wisdem/test/test_drivetrainse/test_layout.py

fix bug in stator and rotor position outputs not being set in geared layout

---

wisdem/inputs/validation.py
wisdem/test/test_ccblade/test_gradients.py

Validate or write yaml only on rank = 0
This wasn't an issue in the past, but the validation started erroring out lately
I also had to loosen a tolerance on some gradients as tests suddenly didn't pass

Validate mpi

---

environment.yml
pyproject.toml
wisdem/inputs/analysis_schema.yaml

Allow safety factor on tip deflection constraint to be smaller than 1 to allow flexible rotors

prep for another minor release. allow to relax tip defl constraint

---

environment.yml
pyproject.toml
wisdem/commonse/utilities.py
wisdem/floatingse/floating_frame.py
wisdem/inputs/modeling_schema.yaml
wisdem/test/test_commonse/test_utilities.py

Minor bug & compatibility fixes to prepare for the WEIS workshop at NAWEA & online.
- Added tower mode shape skipping from @dzalkind 
- Added fix for tower mode shape classification for floating tower from @mayankchetan 
- Restricting moopy to previous release (1.1) --> needs to be resolved  with a more permanent fix in the future.
Tests pass on HPC.

Workshops fixes
