- wisdem/nrelcsm/csmPPI.py
This fixes an import that causes some script using the nrelcsm module to
fail.
> csmPPI-import-bug

- wisdem/glue_code/gc_LoadInputs.py
This is useful when you want to perturb optimization design variables without using the WISDEM driver directly, such as multifidelity optimization cases.
> Allow the user to set opt_flag to True or False in the analysis_options yaml

- docs/wisdem/nrelcsm/theory.rst
Is this a typo? Should it be b instead of kc?
> fix typo in docs

- .flake8
- .isort.cfg
- .pre-commit-config.yaml
- pyproject.toml
- wisdem/glue_code/runWISDEM.py
Tried to follow tips from [here](https://medium.com/staqu-dev-logs/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort-cac8b01e0ea1) and from the ORBIT repo, which has more hooks than this.  I think all you need to do, as a developer, is (from your local WISDEM clone):
`pip install pre-commit`
`pre-commit install`
This will likely need some tweaks as we start using it and get frustrated with various behaviors.
> Precommit hooks

- environment.yml
- wisdem/glue_code/glue_code.py
Adding try around import for orbit to get around no-conda package availability for simpy & marmot
Tested locally, hopefully should run
- [x ] I have run existing tests which pass locally with my changes
> trying to get around conda-forge obstacles

- wisdem/inputs/geometry_schema.yaml
Enforce limits of Poisson ratios in the schema only for isotropic materials. I will update the IEA repo windIO as well.
A wrong upper limit of 0.6 was imposed in the geometry schema yaml for the Poisson ratios of anisotropic materials. New materials for the BAR rotors have Poisson ratios above the older limit of 0.6.
Isotropic materials have Poisson ratios between -1 and 0.5, but anisotropic materials can indeed go outside these bounds
Tests should not be affected
> reset limits poisson ratios

- examples/05_tower_monopile/monopile_direct.py
- examples/05_tower_monopile/tower_direct.py
- examples/09_floating/semi_example.py
- examples/09_floating/spar_example.py
- examples/09_floating/spar_opt.py
- examples/09_floating/tlp_example.py
- wisdem/glue_code/gc_LoadInputs.py
- wisdem/glue_code/gc_WT_DataStruc.py
- wisdem/glue_code/gc_WT_InitModel.py
- wisdem/test/test_floatingse/test_floating.py
- wisdem/test/test_towerse/test_tower.py
- wisdem/towerse/tower.py
This will enable more seamless read and write of the tower grid to the yaml files while leaving all discretization complexity within TowerSE.
> moving all tower discretization content to TowerSE instead of ontology read

- wisdem/glue_code/gc_LoadInputs.py
- wisdem/glue_code/glue_code.py
- wisdem/inputs/modeling_schema.yaml
The component running a single instance of CCBlade and optionally used to determine the twist by inverting the bem equations was not properly connected and the twist was not passed out correctly
Re-instate the ability to determine twist from inverted beam equations
> fix connections blade twist

- wisdem/glue_code/glue_code.py
Fix a little bug: coord_xy_dim is no longer used in the rail transport model
Bug fix
The examples don't currently run the rail transport model... and so we missed the bug in _glue_code.py_
> coord_xy_dim not needed

- wisdem/glue_code/gc_PoseOptimization.py
The default behavior of SNOPT is to check the derivatives using FD.
Since we're only FDing over WISDEM and WEIS (for now), this is irrelevant.
This PR sets the default behavior within WISDEM to skip this check, which saves computational time.
> Set default verify level to -1 to avoid unnecessary FD check on SNOPT

- examples/14_overridden_values/driver.py
- wisdem/ccblade/ccblade_component.py
- wisdem/glue_code/gc_LoadInputs.py
- wisdem/glue_code/gc_PoseOptimization.py
- wisdem/glue_code/glue_code.py
- wisdem/inputs/modeling_schema.yaml
- wisdem/postprocessing/compare_designs.py
- wisdem/rotorse/rotor.py
- wisdem/rotorse/rotor_elasticity.py
- wisdem/rotorse/rotor_power.py
- wisdem/rotorse/rotor_structure.py
- wisdem/test/test_gluecode/test_gc_modified_yaml.py
- wisdem/test/test_gluecode/test_gluecode.py
- wisdem/test/test_rotorse/test_rotor_structure.py
All WISDEM modules have a top-level group that is imported into the glue code except for the Rotor.  There used to be a RotorSE group before the IEAontology4all branch and now things are stable enough to bring it back.  Using some promoted variable names in the RotorSE group also simplifies the glue code quite a bit.  I was also able to catch a few missing connections.
**The downside is that post-processing scripts that access rotor outputs will need to change to add the `rotorse` prefix.** For instance, `rotorse.re.precomp.blade_mass`.
> Rotorse group to simplify glue code

- wisdem/glue_code/gc_WT_InitModel.py
- wisdem/inputs/geometry_schema.yaml
Add ability to overwrite the IEC mean wind speed based on WT wind class, see https://github.com/WISDEM/WISDEM/issues/284
Be able to control the average inflow wind speed
I haven't added any specific example
> ability to overwrite the IEC mean U for aep calcs

- examples/05_tower_monopile/tower_direct.py
- wisdem/inputs/modeling_schema.yaml
- wisdem/towerse/__init__.py
- wisdem/towerse/tower.py
- wisdem/towerse/tower_props.py
- wisdem/towerse/tower_struct.py
This makes the number of sampling points along the tower a modeling options. This was motivated by a case where the tower's mode shape coefficients became too large for ElastoDyn's to handle well. 
The existing testing should capture this.
> TowerSE NREFINE

- wisdem/rotorse/parametrize_rotor.py
Minor bugfix for structural thicknesses used in blade optimization.
To enable spar caps and TE reinforcements, need to draw from the correct output array instead of the input array for thicknesses.
> Bugfix for struct opt thicknesses

- examples/09_floating/tlp_example.py
- wisdem/floatingse/floating_frame.py
- wisdem/glue_code/gc_WT_InitModel.py
- wisdem/glue_code/glue_code.py
- wisdem/test/test_floatingse/test_floating.py
- wisdem/test/test_floatingse/test_frame.py
- wisdem/test/test_pyframe3dd/test_breakdown.py
- wisdem/test/test_towerse/test_tower.py
- wisdem/test/test_towerse/test_tower_struct.py
- wisdem/towerse/tower.py
- wisdem/towerse/tower_props.py
- wisdem/towerse/tower_struct.py
Embarrassing to catch this a year late, but once we moved to using Frame3DD for the drivetrain, RNA mass is accounted for in the tower top forces & moments.  Adding it in again in the tower calcs meant we are double counting it.  I made a quick Frame3DD example unit test to ensure that this is the case.
> Bug in double counting of rna mass

- pyproject.toml
- wisdem/test/test_ccblade/test_gradients.py
- wisdem/test/test_optimization_drivers/test_nlopt_driver.py
Leverage `pyproject.toml` to tell pip to install numpy before running setuptools.
There is a lot of swirl on the Internet about setuptools and numpy.distutils.  Eventually we may have to move away from setuptools, but I'm not positive and for now I think we can wait a bit for that dust to settle.  Hopefully this fix will help with the pip-issues that have been coming up.
Should also fix #348 (crossing fingers)
> tell pip to install numpy first

- .github/workflows/CI_WISDEM.yml
- README.md
- environment.yml
- setup.py
- wisdem/test/test_optimization_drivers/test_nlopt_driver.py
Updates the conda install instructions to be a little more robust and includes `pip install` in our CI builds.  I have also removed `pyside2` from the `setup.py` file as that is the cause of Issue #350
> Include pip in CI (for Linux/Mac), more robust conda instructions

- .github/workflows/CI_WISDEM.yml
- README.md
- docs/installation.rst
- environment.yml
- setup.py
Update install instructions and testing environment to rely on conda version of `pyoptsparse`.  NREL users that want to use the local SNOPT will have to do their own custom install of pyoptsparse from source (working on a WISDEM-org fork).
> Rely on conda version of pyoptsparse

- wisdem/commonse/turbine_class.py
- wisdem/glue_code/gc_LoadInputs.py
- wisdem/glue_code/gc_WT_DataStruc.py
- wisdem/glue_code/gc_WT_InitModel.py
- wisdem/glue_code/glue_code.py
- wisdem/inputs/modeling_schema.yaml
- wisdem/test/test_gluecode/test_gluecode.py
Make the value and definition of the 50-year extreme gust the same across the few modules that were previously using independent values.  User can also now override the vallue.
> Extreme50 consistency

- README.md
- wisdem/glue_code/gc_WT_DataStruc.py
- wisdem/glue_code/gc_WT_InitModel.py
- wisdem/inputs/geometry_schema.yaml
Add tracking of fiber orientation in blade data structure, to pair with 15-MW data update request
> adding tracking of fiber orientation

- wisdem/glue_code/gc_LoadInputs.py
- wisdem/glue_code/gc_PoseOptimization.py
- wisdem/inputs/analysis_schema.yaml
- wisdem/rotorse/rotor_power.py
It's currently possible to run an optimization w/ finer control point distribution (`n_opt`, distributed uniformly) than the analysis nodes (`n_span`, distributed uniformly). The resulting yaml files have the analysis nodes, and information loss/ambiguity w.r.t. the control points will occur. This prevents that from occuring by raising an error if `n_opt` > `n_span`.
Tested against cases that use relevant features.
> Feature nopt/nspan mismatch error

- .github/workflows/Publish_WISDEM.yml
- examples/05_tower_monopile/analysis_options_monopile.yaml
- pyproject.toml
- setup.py
- wisdem/commonse/cylinder_member.py
- wisdem/drivetrainse/drive_structure.py
- wisdem/fixed_bottomse/monopile.py
- wisdem/glue_code/gc_LoadInputs.py
- wisdem/glue_code/gc_PoseOptimization.py
- wisdem/glue_code/glue_code.py
- wisdem/inputs/geometry_schema.yaml
- wisdem/postprocessing/default_modeling_options.yaml
- wisdem/postprocessing/wisdem_get.py
- wisdem/test/test_fixed_bottomse/test_monopile.py
- wisdem/towerse/tower.py
This PR originates from the work with the IEA22 + some improvements coming from the h2@scale project:
- The buckling check on tower and monopile is now done on the entire column, no longer separately on the two. The previous approach caused unrealistic discontinuities at the transition piece
- The tower+monopile optimization example 5 has a better set of constraints
- Activating soil stiffness no longer caused frame3dd to crash, thank you @gbarter. This fix caused an update to the regression test test_monopile.py
- Hub and nacelle equivalent elastic properties are output to the yaml
- Spar caps names are checked also during an optimization
- Code compiles on GitHub Actions Mac, thank you @gbarter and @deslaughter
_Select the appropriate type(s) that describe …
> Monopile and Other various improvements

- wisdem/ccblade/Polar.py
Fix a small bug in Viterna extrapolation code where if `alpha_low == -alpha_high`, then the code repeats the data corresponding to `alpha_low` in the resulting extrapolation. This causes OpenFAST to error out due to duplicate `alpha` in the airfoil polar files.
adds functionality)
Try the Viterna extension with this [code](https://github.com/WISDEM/WISDEM/files/12887481/ViternaExtensionOfDeltaPolars.txt)  (rename code to .py) and with [this](https://github.com/WISDEM/WISDEM/files/12887491/Polar_LowARDelta.txt) file in the same folder.
> Fix Viterna extrapolation bug to avoid repeated data

- examples/09_floating/nrel5mw-semi_oc4.yaml
- wisdem/floatingse/constraints.py
- wisdem/floatingse/floating_system.py
- wisdem/glue_code/gc_PoseOptimization.py
- wisdem/test/test_floatingse/test_constraints.py
Some minor updates to FloatingSE to improve platform optimizations, related to https://github.com/WISDEM/WEIS/pull/223:
I changed the draft/freeboard margin calculations because I suspected an error. I didn't fully understand the previous implementation, so I re-wrote it in a way that made sense.
In pose optimization, make the source period component constraint (or others) depend on some modeling options
> Merge improvements from dzalkind in FloatingSE

- wisdem/drivetrainse/gearbox.py
- wisdem/test/test_drivetrainse/test_gearbox.py
Adjust regression lines behind length and radius (or diameter) of the gearbox. These are now set equal to 1.5% and 0.6% (or 1.2%) of wind turbine rotor diameter
> update regression values for gearbox L and D

- wisdem/glue_code/gc_PoseOptimization.py
The `lower_k` variable was being set where the `upper_k` variable should have been being set.
Correct user constraint setting
> Correct typo in setting user constraints

- wisdem/drivetrainse/layout.py
- wisdem/test/test_drivetrainse/test_layout.py
Fix to address bedplate mass going negative when the turbine is in downwind configuration and has a direct drive system. The limitations of the `np.arctan` function caused a step change in the angles being computed for a downwind turbine. Current fix replaces it with `np.arctan2`. There are no changes in the results for the upwind configuration. I'm open to suggestions to make the fix more pythonic.
New test `testMassValuesDownwind` added to account for downwind turbines with direct-drive systems.
> bedplate mass fix for downwind direct drive systems

- wisdem/commonse/utilities.py
- wisdem/fixed_bottomse/monopile.py
- wisdem/rotorse/rotor_structure.py
- wisdem/test/test_commonse/test_utilities.py
- wisdem/towerse/tower.py
The faster and more robust method continues to give incorrect mode shapes.  The tower ED coefficients for the 22mw are  incorrect.
> Switch to nikhar's rank_and_file method (with vectorization) for ElastoDyn coefficients

- wisdem/floatingse/floating_system.py
- wisdem/glue_code/gc_PoseOptimization.py
When running a WEIS optimization that requires `approx_totals`, we get the following error:
```
Total derivative with respect to 'wisdem.wt.wt_prop.wt_init.floating.joints.jointdv_0' depends upon discrete output variables ['wisdem.wt.floatingse.perf.sys.plat.platform_elem_memid'].
```
Converting discrete outputs/inputs to modeling options was the workaround when we encountered this previously.
`platform_elem_memid` does not seem to be used anywhere else in WISDEM.  It's used to set up OpenFAST inputs in `openmdao_openfast.py`.
> Change platform_elem_memid to a modeling option

- wisdem/glue_code/gc_PoseOptimization.py
- wisdem/glue_code/glue_code.py
- wisdem/inputs/analysis_schema.yaml
- wisdem/test/test_gluecode/test_gluecode.py
- Fix bug that ensures that commissioning and decommissioning costs are included in LandBOSSE figures.
- Add turbine and bos capex costs as optimization merit figures
> bug fixes and feature requests per Nicole

- examples/13_design_of_experiments/analysis_options.yaml
- wisdem/orbit/api/wisdem.py
- wisdem/test/test_gluecode/test_gc_modified_yaml.py
- wisdem/test/test_gluecode/test_gc_yaml_floating.py
- wisdem/test/test_gluecode/test_gluecode.py
Thanks to a Forum [post](https://forums.nrel.gov/t/lcoe-optimization-and-bos-cost/7712/10), we realized that turbine capex was being double counted since it was [also included](https://github.com/WISDEM/ORBIT/blob/dev/ORBIT/manager.py#L1814) in the ORBIT "total_capex" value after the ORBIT overhaul.  This fixes that error.
> Fix bos capex bug

- wisdem/commonse/fileIO.py
- wisdem/glue_code/glue_code.py
Fix a bug where `gearbox_torque_density` wasn't propagated through the glue code correctly, and fix a somewhat mysterious issue with the `prob.model.list_inputs` command from `OpenMDAO 3.38.0`
> Gearbox density

- wisdem/commonse/cylinder_member.py
- wisdem/fixed_bottomse/monopile.py
- wisdem/towerse/tower.py
Fixes the bug identified in the [forums](https://forums.nrel.gov/t/is-the-wisdem-n-refine-parameter-settable-for-the-monopile/8535/4).
> ensuring that nrefine is a user option for both tower and monopile

- wisdem/commonse/utilities.py
[//]: # (Explain the goal of this pull request. If it addresses an existing issue be sure to link to it. Describe the big picture of your changes here, perhaps using a bullet list if multiple changes are done to accomplish a single goal. If it accomplishes multiple goals, it may be best to create separate PR's for each.)
Under certain conditions (observed only in floating towers), the Modal Participation Factor (MPF) provided by pyFrame3DD does not match the actual mode shape. This causes mischaracterization when sorting out the modes shapes, resulting in ElastoDyn tower mode shapes having `nan`'s (we get a zero/sum(zero) condition), causing OpenFAST to fail. Observed this when running floating optimizations for the WEIS workshop, multiple iterations fail to run OpenFAST due to the nan's …
> Handling cases when MPF and mode shapes have mismatch
